# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_negatives <- function(user_input, item_input, num_users, num_items, num_negatives) {
    .Call(`_neuralcf_add_negatives`, user_input, item_input, num_users, num_items, num_negatives)
}

